name: Static Analysis CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Static analysis
        run: |
          clang-tidy \
          $(find src include -name '*.cpp' -o -name '*.hpp') \
          -checks='clang-analyzer-core.uninitialized.*,cppcoreguidelines-pro-type-member-init' \
          -- -std=c++20 -Iinclude
